"""add departmentenduserjoin table

Revision ID: d4081572d04a
Revises: a5f0be5c8b69
Create Date: 2023-09-26 23:49:26.799195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4081572d04a'
down_revision = 'a5f0be5c8b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_app_joins',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('department_id', postgresql.UUID(), nullable=False),
    sa.Column('app_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='department_app_join_pkey'),
    sa.UniqueConstraint('department_id', 'app_id', name='unique_department_app_join')
    )
    with op.batch_alter_table('department_app_joins', schema=None) as batch_op:
        batch_op.create_index('department_app_join_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('department_app_join_department_id_idx', ['department_id'], unique=False)

    op.create_table('department_enduser_joins',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('department_id', postgresql.UUID(), nullable=False),
    sa.Column('enduser_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='department_enduser_join_pkey'),
    sa.UniqueConstraint('department_id', 'enduser_id', name='unique_department_enduser_join')
    )
    with op.batch_alter_table('department_enduser_joins', schema=None) as batch_op:
        batch_op.create_index('department_enduser_join_department_id_idx', ['department_id'], unique=False)
        batch_op.create_index('department_enduser_join_enduser_id_idx', ['enduser_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_enduser_joins', schema=None) as batch_op:
        batch_op.drop_index('department_enduser_join_enduser_id_idx')
        batch_op.drop_index('department_enduser_join_department_id_idx')

    op.drop_table('department_enduser_joins')
    with op.batch_alter_table('department_app_joins', schema=None) as batch_op:
        batch_op.drop_index('department_app_join_department_id_idx')
        batch_op.drop_index('department_app_join_app_id_idx')

    op.drop_table('department_app_joins')
    # ### end Alembic commands ###
